version: 0.1
os: linux
files:
  - source: salt/
    destination: /etc/salt/codedeploy/
  - source: routes/index.js
    destination: /var/www/
hooks:
#  BeforeInstall:
#    - location: deploy_hooks/before_install.sh
#      runas: root
  ApplicationStart:
    - location: npm start
      runas: ec2-user
#  ValidateService:
#    - location: deploy_hooks/verify_service.sh
#      runas: root