version: 0.1
os: linux
files:
  - source: salt/
    destination: /etc/salt/codedeploy/
  - source: routes/index.js
    destination: /var/www/
hooks:
  BeforeInstall:
    - location: echo "EPA" > /tmp/test.txt
      runas: root
  ApplicationStart:
    - location: bin/www
      runas: root
#  ValidateService:
#    - location: deploy_hooks/verify_service.sh
#      runas: root